using Honotop.WMS.Models.Configs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Honotop.WMS.Service.Configs
{
   public interface IConfigService
    {
        /// <summary>
        /// 销售渠道
        /// </summary>
        /// <returns></returns>
        Task<IList<InventoryChannelModel>> GetInventoryChannelListAsync();
        /// <summary>
        /// 仓库列表
        /// </summary>
        /// <returns></returns>
        Task<IList<InventoryChannelModel>> GetWarehouseListAsync();
        /// <summary>
        /// 库存区域
        /// </summary>
        /// <returns></returns>
        Task<IList<InventoryChannelModel>> GetZoneListAsync();
        /// <summary>
        /// 库存状态
        /// </summary>
        /// <returns></returns>
        Task<IList<InventoryChannelModel>> GetInventoryStatusListAsync();
        /// <summary>
        /// 入库类型
        /// </summary>
        /// <returns></returns>
        Task<IList<InventoryChannelModel>> GetReceiptTypeListAsync();
        /// <summary>
        /// 收货状态
        /// </summary>
        /// <returns></returns>
        Task<IList<InventoryChannelModel>> GetInboundStatusListAsync();
        /// <summary>
        /// 承运商
        /// </summary>
        /// <returns></returns>
        Task<IList<InventoryChannelModel>> GetCarrierListAsync();
        /// <summary>
        /// 订单类型
        /// </summary>
        /// <returns></returns>
        Task<IList<InventoryChannelModel>> GetShipmentTypeListAsync();
        /// <summary>
        /// 订单模式 （单品或者多品）
        /// </summary>
        /// <returns></returns>
        Task<IList<InventoryChannelModel>> GetOrderTypeListAsync();
        /// <summary>
        /// 订单处理类型
        /// </summary>
        /// <returns></returns>
        Task<IList<InventoryChannelModel>> GetShipmentProcessTypeListAsync();
        /// <summary>
        /// 订单状态
        /// </summary>
        /// <returns></returns>
        Task<IList<InventoryChannelModel>> GetShipmentStatusListAsync();
        /// <summary>
        /// 销售渠道
        /// </summary>
        /// <returns></returns>
        IList<InventoryChannelModel> GetInventoryChannelList();
        /// <summary>
        /// 仓库列表
        /// </summary>
        /// <returns></returns>
        IList<InventoryChannelModel> GetWarehouseList();
        /// <summary>
        /// 库存区域
        /// </summary>
        /// <returns></returns>
        IList<InventoryChannelModel> GetZoneList();
        /// <summary>
        /// 库存状态
        /// </summary>
        /// <returns></returns>
        IList<InventoryChannelModel> GetInventoryStatusList();
        /// <summary>
        /// 入库类型
        /// </summary>
        /// <returns></returns>
        IList<InventoryChannelModel> GetReceiptTypeList();
        /// <summary>
        /// 收货状态
        /// </summary>
        /// <returns></returns>
        IList<InventoryChannelModel> GetInboundStatusList();
        /// <summary>
        /// 承运商
        /// </summary>
        /// <returns></returns>
        IList<InventoryChannelModel> GetCarrierList();
        /// <summary>
        /// 订单类型
        /// </summary>
        /// <returns></returns>
        IList<InventoryChannelModel> GetShipmentTypeList();
        /// <summary>
        /// 订单模式 （单品或者多品）
        /// </summary>
        /// <returns></returns>
        IList<InventoryChannelModel> GetOrderTypeList();
        /// <summary>
        /// 订单处理类型
        /// </summary>
        /// <returns></returns>
        IList<InventoryChannelModel> GetShipmentProcessTypeList();
        /// <summary>
        /// 订单状态
        /// </summary>
        /// <returns></returns>
        IList<InventoryChannelModel> GetShipmentStatusList();


    }
}
